language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
matrix:
  include:

    - os: osx
      go: 1.10.x
      script:
        - unset -f cd # workaround for https://github.com/travis-ci/travis-ci/issues/8703
        - brew update
        - brew cask install osxfuse
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e09ccdce1048c5e03445
    on_success: change
    on_failure: always
